# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0

    working_directory: ~/react-awesome-login

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:8.12.0

    working_directory: ~/react-awesome-login

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                # - master
                # - develop
                - feature/RAL-7kw3zn3f

      - test:
          requires:
            - build

      - hold:
          type: approval
          requires:
            - test

      - deploy-develop:
          requires:
            - test
            - build
          filters:
            branches:
              only: develop

      - deploy-prod:
          requires:
            - build
            - test
            - hold
          filters:
            branches:
              only: master
